apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config   # nome que backend-deployment e postgres.yaml esperam
  labels:
    app: meu-projeto
data:
  DB_HOST: "postgres"
  DB_PORT: "5432"
  DB_NAME: "meu_banco"
  DB_USER: "postgres"
  NODE_ENV: "development"
  POSTGRES_DB: "meu_banco"
  POSTGRES_USER: "postgres"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config   # nome que frontend-deployment.yaml espera
  labels:
    app: meu-projeto
data:
  API_URL: "http://backend-service:3000"
