apiVersion: v1
kind: Secret
metadata:
  name: db-secret         # corrigido: era "app-secret", mas todos referenciam "db-secret"
  labels:
    app: meu-projeto
type: Opaque
data:
  DB_USER: cG9zdGdyZXM=      # postgres
  DB_PASSWORD: c2VuaGExMjM=  # senha123
  DB_NAME: bWV1X2JhbmNv      # meu_banco
